author: "Phillip M. Alday"
date: "8 September 2022"

project:
  execute-dir: project
  output-dir: docs
  type: website
jupyter: julia-1.8
website:
  title: "Mixed-effects models: All the questions you were too afraid to ask  "
  repo-url: https://github.com/palday/Leipzig2022
  repo-actions: [edit, issue]
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - 01-convergence.qmd
      - 02-shrinkage.qmd
  sidebar:
    style: "floating"
    toc-depth: 4
format:
  html:
    selfcontained: true
    theme: sandstone
    toc: true
    toc-depth: 4
